### PR TITLE
Prettify Admin BSI

### PR DESCRIPTION
**Pull request by Diet-Cola**
Should make life easier, this also changes the /bsi information for players to `Bastion: ##/##` instead of `Bastion: Half Strength`

### CODE REVIEW

**Comment by Diet-Cola** [comment]
image
Preview

**Comment by Diet-Cola** [comment]
#11

**Comment by Maxopoly** [comment]
Could you add the group name and remove the "YYYY/MM/DD"

**Comment by Maxopoly** [comment]
Nice

**Pull request merged**
